set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark'
set -g @tmux-gruvbox-right-status-x '%d.%m.%Y' # e.g.: 30.01.2024
set -g @tmux-gruvbox-right-status-y '%I:%M'
set -g @tmux-gruvbox-right-status-z '#h'

set -g prefix C-a

#setw -g xterm-keys on
set -g mouse on

set-option -g default-terminal "xterm-256color"
set-option -g history-limit 50000

set -sg escape-time 0

set -g base-index 1
setw -g pane-base-index 1

bind -n C-l send-keys -R \; clear-history \; send-keys C-l

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

